### ISSUE TITLE
"Authentication" section matches Images but not Queues doc on docs.rackspace.com

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-queues#29]
This might be an intentional change, but the "Authentication" section on staging does not match the same section in the existing book on docs.rackspace.com. It does, however, match the same section in  the migrated Images doc. It might have been updated to match new common content. However, be sure that the service name is changed to Queues where applicable and that all content is applicable to Queues. 

And change the label for the section in the TOC to "Authentication"

**Comment by stephamon** [comment]
The changes to the Authentication section are intentional, but I did double check and fix all the Cloud "Images" references to "Queues. Also, I've fixed the TOC label :)
