### ISSUE TITLE
Possible inconsistency between docs and actual curl API call

### ISSUE THREAD

**Issue by ycombinator** [rackerlabs/docs-cloud-queues#3]
According to http://docs.rackspace.com/queues/api/v1.0/cq-devguide/content/POST_claimMessages_v1_queues__queue_name__claims_claims-operations.html, the value of the `limit` query parameter can range from 1 to 100, defaulting to 10.

Trying an actual curl call to this API with `limit` set to 15, however, fails with a 400 response. Evidence:

```sh
$ curl \
-X POST \
-H 'X-Auth-Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
-H 'Client-ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{"grace":300,"ttl":120}' \
'https://dfw.queues.api.rackspacecloud.com/v1/XXXXXX/queues/cobros/claims?limit=15'
{
    "title": "Invalid API call",
    "description": "Limit must be at least 1 and may not be greater than 10. "
}
```

**Comment by cyrichardson** [comment]
Thanks, Shaunak. Please see email sent to you and Balaji. The limit parameter was recently researched and the API docs where changed to show 100 as the max -  All originating based on a Disqus comment where the results were ambiguous. I'll update the doc as soon as Balaji sees this and concurs that another change to the docs are needed.

**Comment by ycombinator** [comment]
The documentation is correct. There was an issue in the DFW region which was fixed by the Cloud Queues team. Closing this issue.
