### ISSUE TITLE
Part of URI possibly missing under "List queues"

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-queues#37]
In the book on docs, the URI listed at the top of the section for "List queues" is 

`GET /v1/{project_id}/queues​{?marker,​limit,​detailed}`

On staging, it is just: 

`GET /v1/{project_id}/queues`

Should those query parameters be added?

**Comment by meker12** [comment]
This is OK. Query parameters are included in the table, but in the RST format they are not included in the URI. This matches standards followed by api.rackspace.com. See rackerlabs/docs-migration#73.
