### ISSUE TITLE
Part of URI possibly missing under "Bulk-delete messages by ID"

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-queues#42]
In the book on docs, the URI listed at the top of the section for "Bulk-delete messages by ID" is

`DELETE /v1/{project_id}/queues/{queue_name}/messages​{?ids}`

On staging, it is just:

`DELETE /v1/{project_id}/queues/{queue_name}/messages​`

Should the query parameter be added?

**Comment by meker12** [comment]
This is OK. Query parameters are included in the table, but in the RST format they are not included in the URI. This matches standards followed by api.rackspace.com. See rackerlabs/docs-migration#73.
