### ISSUE TITLE
 Part of URI possibly missing under "Claim messages"

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-queues#44]
In the book on docs, the URI listed at the top of the section for "Claim messages" is

`POST /v1/{project_id}/queues/{queue_name}/claims​{?limit}`

On staging, it is just:

`POST /v1/{project_id}/queues/{queue_name}/claims​​`

Should the query parameter be added?

**Comment by meker12** [comment]
This is OK.  Query parameters are included in the table, but in the RST format they are not included in the URI.  This matches standards followed by api.rackspace.com.  See https://github.com/rackerlabs/docs-migration/issues/73.
