### ISSUE TITLE
Edits for release notes

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-queues#56]
See the markup and comments in the attached Word doc for my suggested edits for the release notes. Please let me know if you have any questions. Thanks!

[Cloud Queues Release Notes_editsKH.docx](https://github.com/rackerlabs/docs-cloud-queues/files/30427/Cloud.Queues.Release.Notes_editsKH.docx)

**Comment by meker12** [comment]
Stephanie integrated the Release Notes with this commit: https://github.com/rackerlabs/docs-cloud-queues/commit/2d81bbbdd5db9ef07d97f47385de22eaea66d672
